services:
  fp9q2x7m4v:
    container_name: fp9q2x7m4v_app
    image: ghcr.io/mr-devloper005/fullprokey.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3073:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
